default: # 기본 옵션
  name: express-template
  port: 8080
  renderer: resources/vue-ssr-server-bundle.json # SSR 파일명
  template: # 사용할 템플릿 파일
    index: index.html

development: # 개발모드 옵션
  name: express-template-development

production: # 배포모드 옵션
  name: express-template-production
  template:
    index: dist/index.html

production-local: # 로컬에서 실행하는 배포모드 옵션
  name: express-template-production
  template:
    index: dist/index.html
